### PR TITLE
Fix the flaky test

### LINKED ISSUE #376: The test `force_union_call` is flakey

### PR DESCRIPTION
**Pull request by EMattfolk**
The equality check for unions did not check for equality, but instead
tried to fit one union into the other. This resulted in some weird
behaviour. Main takeaway: == iff ==.

Closes #376.

### CODE REVIEW

File: sylt-common/src/ty.rs [hunk 1]
```diff
@@ -145,7 +145,7 @@ impl PartialEq for Type {
             (Type::Bool, Type::Bool) => true,
             (Type::String, Type::String) => true,
             (Type::Tuple(a), Type::Tuple(b)) => a.iter().zip(b.iter()).all(|(a, b)| a == b),
-            (Type::Union(a), b) | (b, Type::Union(a)) => a.iter().any(|x| x == b),
+            (Type::Union(a), Type::Union(b)) => a == b,
```
Comment (FredTheDino) [inline sylt-common/src/ty.rs:148]: Nice!

**Review by FredTheDino — APPROVED** [review]
How did you test it?

File: .github/workflows/rust.yml [hunk 2]
```diff
@@ -7,6 +7,7 @@ on:
 
 env:
   CARGO_TERM_COLOR: always
+  RUSTFLAGS: --deny warnings
```
Comment (sornas) [inline .github/workflows/rust.yml:10]: :+1:

**Comment by EMattfolk** [comment]
> How did you test it?

```sh
while cargo run tests/bugs/union_types_376.sy
do
done
```
